name: Build & Upload
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
on:
  workflow_dispatch:
    inputs:
      FILES_TO_EXPECT:
        type: string
        required: false
        default: '-1'
  workflow_call:
    secrets:
      ENVS:
        required: false
    inputs:
      FILES_TO_EXPECT:
        type: string
        required: false
        default: '-1'
      COMMIT_CHANGELOG:
        type: boolean
        required: false
        default: false
      DEBUG_ENABLED:
        type: boolean
        description: 'Run the build with tmate debugging enabled.'
        required: false
        default: false

jobs:
  build-apk:
    name: APK Build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3.5.0

      - name: Update Env for custom build
        run: |
          echo "${{ secrets.ENVS }}" >> .env

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.DEBUG_ENABLED }}

      - name: Build Revanced APKs
        run: |
          docker-compose up --build

      - name: Upload Build APKS
        uses: nikhilbadyal/upload-artifact@count-check
        with:
          name: Built-APKs
          path: |
            apks/*-by-Spacellary.apk
            apks/*-output.apk
            apks/VancedMicroG.apk"
          if-no-files-found: error
          files-to-expect: ${{ inputs.FILES_TO_EXPECT }}

      - name: Commit Update file
        if: ${{ inputs.COMMIT_CHANGELOG }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: changelogs
          skip_checkout: true
          file_pattern: changelog.md
          commit_message: 🚀New Build
          push_options: '--force'
